Sorry: IndentationError: expected an indented block after 'try' statement on line 185 (hs_waypoint_follower.py, line 186)
